# Generated by Django 4.2.3 on 2023-07-08 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_name', models.CharField(max_length=50)),
                ('cs_url', models.CharField(max_length=50)),
                ('cs_username', models.CharField(max_length=100)),
                ('cs_password', models.CharField(max_length=50)),
                ('cs_status', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
