# Generated by Django 4.2.3 on 2023-07-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cs_am',
            field=models.CharField(default='', max_length=50),
        ),
    ]
