# Generated by Django 4.2.3 on 2023-07-10 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_customer_cs_am'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_id', models.CharField(max_length=50)),
                ('cs_am', models.CharField(max_length=100)),
                ('store_id', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=50)),
                ('store_type', models.CharField(max_length=50)),
                ('store_ex_time', models.DateField()),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'CustomerReport',
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='create_at',
        ),
    ]
