# Generated by Django 4.2.3 on 2023-08-18 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_customerreport_remove_customer_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='customerreport',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
